# Generated by Django 5.1.1 on 2025-05-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name": "Локация", "verbose_name_plural": "Локации"},
        ),
    ]
